name: CI/CD

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Set up node.js 14 
      uses: actions/setup-node@v2
      with:
        node-version: 14
        cache: npm
        
    - name: Globally update npm
      run: npm install -g npm@latest

    - name: Install dependencies
      run: npm install -force

    # - name: Run tests
    #   run: npm test 

    - name: Build
      run: npm run build

    - name: Deploy
      run: |
        git remote set-url origin https://github.com/kulmarcin/mapApp.git
        npm run deploy

